<?php
$title = 'Delete user';
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete <br/>
    '<?php echo $this->escapeHtml($user->username); ?>' (<?php echo $this->escapeHtml($user->email); ?>)
    ID: '<?php echo $this->escapeHtml($user->account_id); ?>'?
</p>
<?php
$url = $this->url('user', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $user->account_id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>