<?php
$title = 'My Users';
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('user', array('action'=>'add'));?>">[+] Add new user</a>
</p>

<table class="table table-hover">
<tr>
    <th>ID</th>
    <th>E-mail</th>
    <th>Name</th>
    <th>Balance</th>
    <th>Last Active</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user['account_id']);?></td>
    <td><?php echo $this->escapeHtml($user['email']);?></td>
    <td><?php echo $this->escapeHtml($user['first_name'])." ".$this->escapeHtml($user['last_name']);?></td>
    <td><?php 
        $bal = $this->escapeHtml($user['balance']);
        $fmt = number_format($bal);
        if($bal > 100000) echo '<span style="color:green">+'.$fmt.'</span>';
        else if($bal > 0) echo '<span style="color:gold">+'.$fmt.'</span>';
        else              echo '<span style="color:red">'.$fmt.'</span>';
    ?></td>
    <td><?php echo $this->escapeHtml($user['updated_at']);?></td>
    <td>
        <a href="<?php echo $this->url('user',
            array('action'=>'view', 'id' => $user['account_id']));?>">[O] View</a> | 
        <a href="<?php echo $this->url('user',
            array('action'=>'edit', 'id' => $user['account_id']));?>">[#] Edit</a> | 
        <a href="<?php echo $this->url('user',
            array('action'=>'delete', 'id' => $user['account_id']));?>">[-] Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>