<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('DoctorPay - Payment Gateway') ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath('styles/custom.css'))
                    ->prependStylesheet($this->basePath('css/fonts.css'))
                    ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                    ->prependStylesheet($this->basePath('scripts/camera/css/camera.css'))
                    ->prependStylesheet($this->basePath('scripts/bootstrap/css/bootstrap-responsive.min.css'))
                    ->prependStylesheet($this->basePath('scripts/bootstrap/css/bootstrap.min.css'))
                     
    ?>
    
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>

<?php  
    $auth = new Zend\Authentication\AuthenticationService();
?>

<body id="pageBody">

<div id="divBoxed" class="container">

    <div class="transparent-bg" style="position: absolute;top: 0;left: 0;width: 100%;height: 100%;z-index: -1;zoom: 1;"></div>

    <div class="divPanel notop nobottom">
            <div class="row-fluid">
                <div class="span12">

                    <div id="divLogo">
                        <img src="<?php echo $this->basePath('img/doctorpay-logo.png') ?>"><div id="divHeaderLine2"> - Online Payment Gateway </div>
                    </div>

	            </div>
            </div>   
            <div class="row-fluid">
                <div class="span12">
    					
                    <div id="divMenuRight" class="pull-right">
                    <div class="navbar">
                        <button type="button" class="btn btn-navbar-highlight btn-large btn-primary" data-toggle="collapse" data-target=".nav-collapse">
                            Navigation <span class="icon-chevron-down icon-white"></span>
                        </button>
                        <div class="nav-collapse collapse">
                            <ul class="nav nav-pills ddmenu">
                                <li class="dropdown active"><a href="<?php echo $this->basePath(); ?>">Home</a></li>
                                <li class="dropdown"><a href="#">Service</a></li>
                                <li class="dropdown"><a href="<?php echo $this->basePath()."/user"; ?>">Admin</a></li>
                                <?php if ($auth->hasIdentity()) : ?>
                                <li class="dropdown"><a href="<?php echo $this->basePath()."/user/logout"; ?>">
                                        Logout (<?php echo $auth->getIdentity(); ?>)</a></li>
                                <?php else : ?>
                                <li class="dropdown"><a href="<?php echo $this->basePath()."/user/login"; ?>">Login</a></li>
                                <?php endif ?>
                            </ul>
                        </div>
                    </div>
                    </div>

	            </div>
            </div>
   
    </div>

    <div class="contentArea">

        <div class="divPanel notop page-content">

            <!-- content begin -->
            <?php echo $this->content; ?>
            <!-- content end -->

            <div id="footerInnerSeparator"></div>
        </div>
    </div>

    <div id="footerOuterSeparator"></div>

    <div id="divFooter" class="footerArea">

        <div class="divPanel">
<?php /*
            <div class="row-fluid">
                <div class="span3" id="footerArea1">
                </div>
                <div class="span3" id="footerArea2">
                </div>
                <div class="span3" id="footerArea3">
                </div>
                <div class="span3" id="footerArea4">
                </div>
            </div>
*/ ?>
            <div class="row-fluid">
                <div class="span12">
                    <p class="copyright">
                        Copyright © 2015 Dotsiam. All Rights Reserved. 
                    </p>

                    <p class="social_bookmarks">
                        <a href="#"><i class="fa fa-facebook"></i> Facebook</a>
			<a href="#"><i class="fa fa-twitter"></i> Twitter</a>
			<a href="#"><i class="fa fa-instagram"></i> Instagram</a>
			<a href="#"><i class="fa fa-rss"></i> Rss</a>
                    </p>
                </div>
            </div>

        </div>
    </div>
</div>
<br /><br /><br />


<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath('scripts/camera/scripts/jquery.mobile.customized.min.js'))
    ->prependFile($this->basePath('scripts/easing/jquery.easing.1.3.js'))
    ->prependFile($this->basePath('scripts/camera/scripts/camera.min.js'))
    ->prependFile($this->basePath('scripts/default.js'))
    ->prependFile($this->basePath('scripts/bootstrap/js/bootstrap.min.js'))
    ->prependFile($this->basePath('scripts/jquery-1.8.2.min.js'))
; ?>

<script type="text/javascript">function startCamera() {$('#camera_wrap').camera({ fx: 'scrollLeft', time: 2000, loader: 'none', playPause: false, height: '65%', pagination: true });}$(function(){startCamera()});</script>

<?php echo $this->inlineScript() ?>
</body>
</html>