<div class="row-fluid">
    <div class="span12">

        <div id="headerSeparator"></div>

        <div class="row-fluid">
            <div class="span6">

                <div id="divHeaderText" class="page-content">
                    <div id="divHeaderLine1">ระบบชำระเงินออนไลน์</div><br />
                    <div id="divHeaderLine2">“ดอกเตอร์เพย์” ผู้ให้บริการระบบชำระเงินออนไลน์ หลากหลายช่องทางการรับชำระเงิน เช่น บัตรเครดิต เงินสด บัญชีธนาคารออนไลน์ สามารถรองรับกลุ่มเป้าหมายของร้านค้าได้ทุกความต้องการ</div><br />
                    <div id="divHeaderLine3"><a class="btn btn-large btn-secondary" href="#">รายละเอียดเพิ่มเติม</a>    <a class="btn btn-large btn-primary" href="<?php echo $this->basePath().'/user/add'; ?>">สมัครใช้บริการ</a></div>
                </div>

            </div>
            <div class="span6">

                <div id="camera_wrap">
    <div data-src="styles/working-on-keyboard.JPG" ><div style="position:absolute;bottom:10%;left:3%;padding:10px;width:50%;" class="fadeIn camera_effected camera_caption cap1">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</div></div><div data-src="styles/two-businessmen.jpg" ><div class="camera_caption fadeFromBottom cap2">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</div></div>
                </div>

            </div>
        </div>

        <div id="headerSeparator2"></div>

    </div>
</div>
<br/>
<div class="row-fluid">
    <div class="span12" id="divMain">
<?php /*
        <h1>Welcome</h1>

        <p>Content on this page is for presentation purposes only. Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
        Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </p>
*/ ?>
        <br />

        <div class="row-fluid" style="text-align: center;">
            <div class="span4">
                <h2>สะดวก</h2>
                <span class="fa-stack fa-5x">
                    <i class="fa fa-circle fa-stack-2x" style="color: #bd0000;"></i>
                    <i class="fa fa-clock-o fa-stack-1x fa-inverse"></i>
                </span>             
                <p>หลากหลายช่องทางการชำระเงิน <br/>
                    ไม่ต้องวางการันตี <br/>
                    ระบบเชื่อมต่อง่าย ไม่ยุ่งยาก</p>
            </div>
            <div class="span4">                
                <h2>ปลอดภัย</h2>
                <span class="fa-stack fa-5x">
                    <i class="fa fa-circle fa-stack-2x" style="color: #bd0000;"></i>
                    <i class="fa fa-shield fa-stack-1x fa-inverse"></i>
                </span>     
                <p>มาตราฐานความปลอดภัยทางการเงินระดับสากล  <br/>
                   ด้วยระบบ SSL และมีทีมงานเฉพาะทาง  <br/>
                   ในการตรวจสอบรายการทุจริต</p>
            </div>
            <div class="span4">                
                <h2>เข้าใจคุณ</h2>                
                <span class="fa-stack fa-5x">
                    <i class="fa fa-circle fa-stack-2x" style="color: #bd0000;"></i>
                    <i class="fa fa-hand-o-up fa-stack-1x fa-inverse"></i>
                </span>     
                <p>ให้คำปรึกษาและช่วยเหลือ  <br/>
                    เพื่อตอบรับทุกความต้องการ  <br/>
                    ให้ตรงกับธุรกิจของคุณ</p>
            </div>
        </div>  
        
        <h1>ข่าวสาร</h1>
        
        <div class="row-fluid" style="text-align: center;">
            <div class="span4">
                <img src="http://placehold.it/300x150/e7e7e7" class="img-polaroid" style="margin:5px 0px 15px;">                
            </div>
            <div class="span4">                
                <img src="http://placehold.it/300x150/e7e7e7" class="img-polaroid" style="margin:5px 0px 15px;">  
            </div>
            <div class="span4">                
                <img src="http://placehold.it/300x150/e7e7e7" class="img-polaroid" style="margin:5px 0px 15px;">  
            </div>
        </div>  

    </div>
</div>